@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}

@inval_id = 1


@id = 649c6d0376db4e0f931c44b6
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RfdGVzdCIsImlkIjoiNjQ5YzYwNzlkNzY4NGE1MDAwYWYzYTAxIiwiaWF0IjoxNjg3OTcwNzUwLCJleHAiOjE2ODc5NzQzNTB9.skLmtTKNfwq57BmiSuH06D8IZKivk53dApipAKsMRLw 

###
GET http://{{host}}/api/blogs HTTP/1.1

###
POST http://{{host}}/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Test",
    "author": "Test author",
    "url": "Test URI",
    "likes": 5
}

###
PUT http://{{host}}/api/blogs/{{id}} HTTP/1.1
Content-Type: application/json

{
    "title": "Test title",
    "author": "Test author",
    "url": "Test URI",
    "likes": 5
}

###
DELETE http://{{host}}/api/blogs/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}