@hostname = localhost
@port = 3003
@host = {{hostname}}:{{port}}



### Get all blogs
# @name getAll
GET http://{{host}}/api/blogs HTTP/1.1

### Login
# @name login
POST http://{{host}}/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "bugs",
    "password": "bunny"
}

### Add blog
@token = {{login.response.body.token}}
POST http://{{host}}/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Sherlok Holms 3",
    "author": "Artur Conondoil",
    "url": "Test URI",
    "likes": 5
}

### Add likes
@validID = {{getAll.response.body.$[0].id}}
PUT http://{{host}}/api/blogs/{{validID}} HTTP/1.1
Content-Type: application/json

{
    "title": "Test title",
    "author": "Test author",
    "url": "Test URI",
    "likes": 555
}

###
@validID = {{getAll.response.body.$[0].id}}
@token = {{login.response.body.token}}
DELETE http://{{host}}/api/blogs/{{validID}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}