@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}

###
GET http://{{host}}/api/persons

###
@valid_id = 1
http://{{host}}/api/persons/{{valid_id}}

###
@invalid_id = 999
http://{{host}}/api/persons/{{invalid_id}}