@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
@valid_id = 6495d855cac8edc5e9d92e1f
@inval_id = 6495a6c6e2eaf1f02ac062df

###
GET http://{{host}}/api/persons

### Get person
GET http://{{host}}/api/persons/{{valid_id}}

### Get person
GET http://{{host}}/api/persons/{{inval_id}}

### Delete
DELETE http://{{host}}/api/persons/{{valid_id}}

### Delete
DELETE http://{{host}}/api/persons/{{inval_id}}

###
@name="Mike6"
@number="+123-123-123-3"
POST http://{{host}}/api/persons HTTP/1.1
Content-Type: application/json

{
    "name":{{name}},
    "number":{{number}}
}