### Get all patients 
GET http://localhost:3001/api/patients HTTP/1.1
Content-Type: application/json



### Add new patient
POST http://localhost:3001/api/patients HTTP/1.1
Content-Type: application/json

{
  "name": "Test", 
  "dateOfBirth": "Test", 
  "ssn": "Test", 
  "gender": "male", 
  "occupation": "Test"
}

### Add new patient
POST http://localhost:3001/api/patients HTTP/1.1
Content-Type: application/json

{
  "dateOfBirth": "Test", 
  "ssn": "Test", 
  "gender": "male", 
  "occupation": "Test"
}

### Add new patient
POST http://localhost:3001/api/patients HTTP/1.1
Content-Type: application/json

{
  "name": 1, 
  "dateOfBirth": "Test", 
  "ssn": "Test", 
  "gender": "male", 
  "occupation": "Test"
}

### Add new patient
POST http://localhost:3001/api/patients HTTP/1.1
Content-Type: application/json

{
  "name": "Test", 
  "dateOfBirth": 2, 
  "ssn": "Test", 
  "gender": "male", 
  "occupation": "Test"
}

### Add new patient
POST http://localhost:3001/api/patients HTTP/1.1
Content-Type: application/json

{
  "name": "Test", 
  "dateOfBirth": "Test", 
  "ssn": 3, 
  "gender": "male", 
  "occupation": "Test"
}

### Add new patient
POST http://localhost:3001/api/patients HTTP/1.1
Content-Type: application/json

{
  "name": "Test", 
  "dateOfBirth": "Test", 
  "ssn": "Test", 
  "gender": 3, 
  "occupation": "Test"
}

### Add new patient
POST http://localhost:3001/api/patients HTTP/1.1
Content-Type: application/json

{
  "name": "Test", 
  "dateOfBirth": "Test", 
  "ssn": "Test", 
  "gender": "male", 
  "occupation": 4
}

### get patient
GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667 HTTP/1.1
Content-Type: application/json